"""add docs table

Revision ID: 0224945830d6
Revises: 7ca0356a8dda
Create Date: 2019-07-06 00:21:35.519593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0224945830d6'
down_revision = '7ca0356a8dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
