"""modify user table

Revision ID: 1b8000e07ece
Revises: 9118cead7ef8
Create Date: 2019-07-05 00:36:24.823409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8000e07ece'
down_revision = '9118cead7ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
