"""Added account table

Revision ID: 1d432aec2cab
Revises: f2483e53dfdd
Create Date: 2019-06-25 01:02:29.535418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d432aec2cab'
down_revision = 'f2483e53dfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
