"""modify user table

Revision ID: 1e4d04364acd
Revises: 93f8602e7736
Create Date: 2019-07-05 17:29:12.709656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4d04364acd'
down_revision = '93f8602e7736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
