"""add archive column location table

Revision ID: 27b0b4a0170b
Revises: 74178d15e500
Create Date: 2019-07-07 20:46:07.567595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27b0b4a0170b'
down_revision = '74178d15e500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('archive', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('locations', sa.Column('context', sa.String(length=10), nullable=True))
    op.drop_column('locations', 'context_point')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('context_point', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('locations', 'context')
    op.drop_column('locations', 'archive')
    # ### end Alembic commands ###
