"""modify user table

Revision ID: 33e3a4b7ba37
Revises: 0224945830d6
Create Date: 2019-07-06 17:38:28.728821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e3a4b7ba37'
down_revision = '0224945830d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
