"""Added account table

Revision ID: 36a14f7b454c
Revises: 3ac7ef01e52e
Create Date: 2019-06-25 00:39:23.271219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a14f7b454c'
down_revision = '3ac7ef01e52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
