"""Added account table

Revision ID: 3ac7ef01e52e
Revises: 52a145329745
Create Date: 2019-06-25 00:38:32.226690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ac7ef01e52e'
down_revision = '52a145329745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chattype', sa.String(length=10), nullable=True))
    op.drop_column('users', 'chatid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chatid', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('users', 'chattype')
    # ### end Alembic commands ###
