"""Added account table

Revision ID: 4ffd63857805
Revises: 6a873a2fc669
Create Date: 2019-06-25 01:06:18.635977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffd63857805'
down_revision = '6a873a2fc669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
