"""Added account table

Revision ID: 52a145329745
Revises: 5ed0424f91e2
Create Date: 2019-06-23 22:05:31.712953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52a145329745'
down_revision = '5ed0424f91e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chatid', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('userid', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=10), nullable=True))
    op.drop_column('users', 'fullname')
    op.drop_column('users', 'name')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('fullname', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('users', 'username')
    op.drop_column('users', 'userid')
    op.drop_column('users', 'chatid')
    # ### end Alembic commands ###
