"""Added account table

Revision ID: 5ed0424f91e2
Revises: c4df6892d5e9
Create Date: 2019-06-23 21:53:06.447748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed0424f91e2'
down_revision = 'c4df6892d5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
