"""Added account table

Revision ID: 6a873a2fc669
Revises: 1d432aec2cab
Create Date: 2019-06-25 01:03:46.291004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a873a2fc669'
down_revision = '1d432aec2cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
