"""modify user table

Revision ID: 6c8469c1b35c
Revises: 1b8000e07ece
Create Date: 2019-07-05 00:38:53.342615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8469c1b35c'
down_revision = '1b8000e07ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
