"""add archive column doc table

Revision ID: 74178d15e500
Revises: de6e2e7db970
Create Date: 2019-07-06 19:24:00.117609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74178d15e500'
down_revision = 'de6e2e7db970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
