"""modify user table

Revision ID: 7ca0356a8dda
Revises: d070fbd965e5
Create Date: 2019-07-05 19:18:11.910117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca0356a8dda'
down_revision = 'd070fbd965e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
