"""modify user table

Revision ID: 9118cead7ef8
Revises: b50764589825
Create Date: 2019-07-05 00:28:42.326850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9118cead7ef8'
down_revision = 'b50764589825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
