"""modify user table

Revision ID: 93f8602e7736
Revises: c2d897247a84
Create Date: 2019-07-05 01:43:22.986274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f8602e7736'
down_revision = 'c2d897247a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
