"""add chars doc table

Revision ID: 9a56cff52764
Revises: 33e3a4b7ba37
Create Date: 2019-07-06 17:45:31.968236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a56cff52764'
down_revision = '33e3a4b7ba37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
