"""Added account table

Revision ID: 9e499ba0816f
Revises: e6151bb644af
Create Date: 2019-06-25 00:59:11.095465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e499ba0816f'
down_revision = 'e6151bb644af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
