"""modify user table

Revision ID: b50764589825
Revises: fc9082e82394
Create Date: 2019-07-05 00:19:50.786254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b50764589825'
down_revision = 'fc9082e82394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('context_point', sa.String(length=10), nullable=True))
    op.add_column('locations', sa.Column('userid', sa.String(length=10), nullable=True))
    op.drop_column('locations', 'username')
    op.drop_column('locations', 'context')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('context', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('locations', sa.Column('username', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('locations', 'userid')
    op.drop_column('locations', 'context_point')
    # ### end Alembic commands ###
