"""modify user table

Revision ID: c2d897247a84
Revises: 6c8469c1b35c
Create Date: 2019-07-05 00:56:22.633732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d897247a84'
down_revision = '6c8469c1b35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
