"""Added account table

Revision ID: c4df6892d5e9
Revises: 878908b3aa3d
Create Date: 2019-06-23 21:51:54.656445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4df6892d5e9'
down_revision = '878908b3aa3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
