"""add table maps

Revision ID: ca81fec55e5c
Revises: e8031a63865b
Create Date: 2019-07-07 21:15:18.214636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca81fec55e5c'
down_revision = 'e8031a63865b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
