"""modify user table

Revision ID: d070fbd965e5
Revises: 1e4d04364acd
Create Date: 2019-07-05 19:11:40.655647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd070fbd965e5'
down_revision = '1e4d04364acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
