"""add archive column location table

Revision ID: dc8080e9bf0a
Revises: 27b0b4a0170b
Create Date: 2019-07-07 20:50:37.732994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8080e9bf0a'
down_revision = '27b0b4a0170b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
