"""Added account table

Revision ID: e6151bb644af
Revises: 45eb4f3519c7
Create Date: 2019-06-25 00:48:41.610991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6151bb644af'
down_revision = '45eb4f3519c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
