"""add table maps

Revision ID: e8031a63865b
Revises: dc8080e9bf0a
Create Date: 2019-07-07 21:11:30.455321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8031a63865b'
down_revision = 'dc8080e9bf0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
