"""Added account table

Revision ID: f2483e53dfdd
Revises: 9e499ba0816f
Create Date: 2019-06-25 01:01:18.576382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2483e53dfdd'
down_revision = '9e499ba0816f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
