"""add archive column doc table

Revision ID: f95eaf2f98ba
Revises: 9a56cff52764
Create Date: 2019-07-06 19:14:49.931717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95eaf2f98ba'
down_revision = '9a56cff52764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc', sa.Column('archive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc', 'archive')
    # ### end Alembic commands ###
