"""modify user table

Revision ID: fc9082e82394
Revises: 4ffd63857805
Create Date: 2019-07-04 18:52:50.132732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9082e82394'
down_revision = '4ffd63857805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('context', sa.String(length=10), nullable=True))
    op.add_column('locations', sa.Column('timestamp', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('locations', 'timestamp')
    op.drop_column('locations', 'context')
    # ### end Alembic commands ###
