version: '2'
services:

  push_app:
    image: jacvmos/push_app:{{tag}}
    volumes:
        - /app/src:/usr/src/app
        - /app/data/:/usr/src/app/data
    links:
      - redisdb:redisdb
      - mysqldb:mysqldb
    depends_on:
      - mysqldb

  bot_app:
    image: jacvmos/bot_app:{{tag}}
    volumes:
        - /app/src:/usr/src/app
        - /app/data/:/usr/src/app/data
    links:
      - redisdb:redisdb
      - mysqldb:mysqldb
    depends_on:
      - mysqldb

  messenger_worker:
    image: jacvmos/celery_app:{{tag}}
    volumes:
        - /app/src:/usr/src/app
        - /app/data/:/usr/src/app/data
    links:
      - redisdb:redisdb
      - mysqldb:mysqldb
    depends_on:
      - mysqldb


  redisdb:
    image: redis:latest

  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD={{mysql_root[0]}}
      - MYSQL_DATABASE={{mysql_db[0]}}
      - MYSQL_USER={{mysql_user[0]}}
      - MYSQL_PASSWORD={{mysql_password[0]}}
    volumes:
      - /app/data/mysql:/var/lib/mysql
      - /app/config/mycustom.cnf:/etc/mysql/conf.d/custom.cnf

volumes:
  my-datavolume: