version: '2'
services:

  push_app:
    image: jacvmos/push_app:{{tag[0]}}
    volumes:
        - /app/src:/usr/src/app
        - /app/data/:/usr/src/app/data
    links:
      - redis:redisdb

  bot_app:
    image: jacvmos/bot_app:{{tag[0]}}
    volumes:
        - /app/src:/usr/src/app
        - /app/data/:/usr/src/app/data
    links:
      - redis:redisdb
      - mysql:mysqldb

  messenger_worker:
    image: jacvmos/celery_app:{{tag[0]}}
    volumes:
        - /app/src:/usr/src/app
        - /app/data/:/usr/src/app/data
    links:
      - redis:redisdb
      - mysql:mysqldb

  redis:
    image: redis:latest

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD={{mysql_root[0]}}
      - MYSQL_DATABASE={{mysql_db[0]}}
      - MYSQL_USER={{mysql_user[0]}}
      - MYSQL_PASSWORD={{mysql_password[0]}}