"""Migrations

Revision ID: 03b3a9173c25
Revises: 052b24537b1f
Create Date: 2019-07-23 01:36:37.163442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b3a9173c25'
down_revision = '052b24537b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
