"""Migrations

Revision ID: 052b24537b1f
Revises: 3e4bd450ea8b
Create Date: 2019-07-23 01:19:09.141201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052b24537b1f'
down_revision = '3e4bd450ea8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc', sa.Column('read', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc', 'read')
    # ### end Alembic commands ###
