"""Migrations

Revision ID: 3c9fc4248e80
Revises: 03b3a9173c25
Create Date: 2019-07-23 02:04:57.135272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c9fc4248e80'
down_revision = '03b3a9173c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc', sa.Column('publish', sa.Boolean(), server_default='1', nullable=False))
    op.drop_column('doc', 'readed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc', sa.Column('readed', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
    op.drop_column('doc', 'publish')
    # ### end Alembic commands ###
