"""Added account table

Revision ID: 3e4bd450ea8b
Revises: 7d1b9a6e0c11
Create Date: 2019-07-11 20:15:53.375245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4bd450ea8b'
down_revision = '7d1b9a6e0c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
