"""add table sensors

Revision ID: 5d66460b512a
Revises: 93fa83e1e66e
Create Date: 2019-07-23 16:54:53.863938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d66460b512a'
down_revision = '93fa83e1e66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
