"""add table sensors

Revision ID: 93fa83e1e66e
Revises: f6b833a857c4
Create Date: 2019-07-23 16:52:38.204890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fa83e1e66e'
down_revision = 'f6b833a857c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
