"""add publish migrations

Revision ID: f6b833a857c4
Revises: 3c9fc4248e80
Create Date: 2019-07-23 02:06:59.728699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b833a857c4'
down_revision = '3c9fc4248e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('publish', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps', 'publish')
    # ### end Alembic commands ###
