---

- name: create configs
  template: src=templates/config.ini dest=/app/src/config.ini

- name: create composer
  template: src=templates/docker-compose.yml dest=/tmp/build/docker-compose.yml
#- name: removing old containers
#  shell: cd /tmp/build/ && docker-compose down
- name: create containers
  shell: cd /tmp/build/ && docker-compose up -d
#- name: removing old imges
#  shell: docker images -q |xargs docker rmi