---
- name: Set authorized key
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
- name: creating app dirs
  file: path={{item}} state=directory mode=0777 recurse=yes
  with_items:
    - /app/data/docs
    - /app/data/maps
    - /app/data/images
    - /app/data/graph
    - /app/data/mysql
    - /app/src
- name: cloning project
  git: repo=https://github.com/Jackvillian/sibay.git dest=/tmp/build force=yes version=release

- name: moving source projects
  copy: remote_src=True src=/tmp/build/monitor_apps/src/ dest=/app/src/ force=yes

- name: create config.ini
  template: src=templates/config.ini dest=/app/src/config.ini
- name: create alembic.ini
  template: src=templates/alembic.ini dest=/app/src/alembic.ini

- name: create config mysql
  template: src=templates/mycustom.cnf dest=/app/config/mycustom.cnf

- name: create composer
  template: src=templates/docker-compose.yml dest=/tmp/build/docker-compose.yml

- name: create containers
  shell: cd /tmp/build/ && docker-compose up -d
