---
- hosts: sibay_air
  user: root
  become: yes
  vars:
    tag:
      - latest
    redis_tag:
      - latest
    mysql_tag:
      - latest
    max_distance:
      - 15.0

  vars_files:
      - vars/secret.yml

  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python2)

  roles:
     #- {role: bootstrap, tags: ['install', 'bootstrap']}
     - {role: deploy, tags: ['install','deploy']}