---
- hosts: sibay_air
  user: root
  become: yes
  vars:
    tag:
      - 0.0.1
    redis_tag:
      - latest
    mysql_tag:
      - latest
  vars_files:
      - vars/secret.yml

  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (yum update && yum install -y python2)

  roles:
     #- {role: bootstrap, tags: ['install', 'bootstrap']}
     - {role: deploy, tags: ['install','deploy']}